name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2

      - name: Npm install
        run: npm install

      - name: Lint check
        run: npm run eslint

      - name: Code format check
        run: npm run prettier

      - name: Type check
        run: npm run typescript

      - name: Tests
        run: npm run typescript

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2

      - name: Get app version
        run: |
          version=`grep '"version"' package.json | cut -d '"' -f 4 | head -n1`
          echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV

      - name: Docker build
        run: |
          docker build . --file Dockerfile \
          --tag techshiftltd/node-rest-api-template:$PACKAGE_VERSION \
          --tag techshiftltd/node-rest-api-template:latest

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push techshiftltd/node-rest-api-template:$PACKAGE_VERSION
          docker push techshiftltd/node-rest-api-template:latest
